### ISSUE TITLE
Cannot unmarshal value of UNH segments when destination is slice

### ISSUE THREAD

**Issue by justin-wilxite** [shogg/edifact#14]
Hello

Thanks for this package. I believe I have found a bug. This test (based on unmarshal_test.go) passes:

```go
var ediMessage = `UNA:+.? '
UNB+UNOC:3+sender+receiver+060620:0931+1++1234567'
UNH+1+DESADV:D:96A:UN'
BGM+220+B10001'
DTM+17:20060620:102'
RFF+ON+1'
RFF+DQ+2'
NAD+BY+++name+street+city++23436+xx'
CPS+'
LIN+1++product A:SA'
QTY+12:10'
CNT+2:1'
UNT+9+1'`

type Item struct {
	ItemNr      int    `edifact:"SG10/SG17/LIN+?"`
	Description string `edifact:"SG10/SG17/LIN+++?"`
	Quantity    int    `edifact:"SG10/SG17/QTY+12:?"`
}
type Message struct {
	ID         string    `edifact:"UNH+?"`
	Date       time.Time `edifact:"DTM+17|18"`
	DeliveryNr string    `edifact:"SG1/RFF+VN|DQ+?"`
	OrderNr    int       `edifact:"SG1/RFF+ON+?"`
	Items      []Item    `edifact:"SG10/SG17"`
}

document := strings.NewReader(ediMessage)
var message Message
err := edifact.Unmarshal(document, &message)
require.NoError(t, err)
assert.Equal(t, "1", message.ID)
```

Changing the test slightly so that the destination is a slice, fails:

```go
document := strings.NewReader(ediMessage)
var messages []*Message
err := edifact.Unmarshal(document, &messages)
require.NoError(t, err)
```

It causes a panic:

```
panic: reflect: slice index out of range

goroutine 7 [running]:
testing.tRunner.func1.2({0x5e27c0, 0x690170})
	/usr/lib/go-1.23/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
	/usr/lib/go-1.23/src/testing/testing.go:1635 +0x35e
panic({0x5e27c0?, 0x690170?})
	/usr/lib/go-1.23/src/runtime/panic.go:785 +0x132
reflect.Value.Index({0x5df600?, 0xc0000121f8?, 0x0?}, 0x0?)
	/usr/lib/go-1.23/src/reflect/value.go:1415 +0x167
github.com/shogg/edifact/build.(*sliceProvider).getValue(0xc000012240, 0x8?)
```

It seems to be specific to the UNH segment.

**Comment by shogg** [comment]
I implemented a quick and easy workaround.
Problem was the ordering of nodes in the decode-tree. The root-node was added last. Now it is added at the beginning.
I somewhat included your test case as `TestUnmarshalIssue14` in `unmarshal_test.go`. `Message` defines a ID field with a value from UNH.

**Comment by justin-wilxite** [comment]
Thank you, that fixes it for me
